name: Build MCP Servers

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-container.yaml

    strategy:
      matrix:
        image_name: [ 'awesome-copilot', 'markdown-to-html', 'todo-list' ]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    with:
      image_name: ${{ matrix.image_name }}
      force: true
    secrets: inherit
