name: Build MCP Server - Awesome Copilot

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-container.yaml
    strategy:
      matrix:
        image_name: [ 'awesome-copilot' ]
        extension: [ 'stdio', 'http' ]
    with:
      image_name: ${{ matrix.image_name }}
      extension: ${{ matrix.extension }}
    secrets: inherit
