name: Build MCP Servers

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-container.yaml

    strategy:
      matrix:
        image_name: [ 'markdown-to-html', 'todo-list' ]
        extension: [ 'stdio', 'http' ]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    with:
      image_name: ${{ matrix.image_name }}
      extension: ${{ matrix.extension }}
      force: true
    secrets: inherit

  build-and-push-image-awesome-copilot-stdio:
    uses: ./.github/workflows/build-container.yaml

    needs: build-and-push-image

    strategy:
      matrix:
        image_name: [ 'awesome-copilot']
        extension: [ 'stdio' ]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    with:
      image_name: ${{ matrix.image_name }}
      extension: ${{ matrix.extension }}
      force: true
    secrets: inherit

  build-and-push-image-awesome-copilot-http:
    uses: ./.github/workflows/build-container.yaml

    needs: build-and-push-image-awesome-copilot-stdio

    strategy:
      matrix:
        image_name: [ 'awesome-copilot' ]
        extension: [ 'http' ]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    with:
      image_name: ${{ matrix.image_name }}
      extension: ${{ matrix.extension }}
      force: true
    secrets: inherit
